### ISSUE TITLE
New FTP Command: SIZE

### ISSUE THREAD

**Issue by ghost** [eclipse-ecal/fineftp-server#19]
There is a FTP command (file size) that I needed, and it's not implemented in fineFTP.
If this request is eligible, I can implement this command and create a pull request.

[Definition of SIZE command in RFC-3659](https://datatracker.ietf.org/doc/html/rfc3659#section-4)

**Comment by FlorianReimold** [comment]
Hi Saeed,

Yea, awesome, if you can implement the command we can merge it to this repository! :)
If I read the RFC correctly, this would also mean you have to implement the FEAT command.

I am curious, what you need the SIZE command for. To make fineFTP compatible with some existing software, or for some custom client?

Regards
Florian

Edit: Oh wow, even in 2007 they are still [forcing to support FTP ASCII mode ](https://datatracker.ietf.org/doc/html/rfc3659#section-4.4), which may compute a different size due to different line endings.

**Comment by FlorianReimold** [comment]
Released in 1.3.0
