### ISSUE TITLE
can it generate an ftp client?

### ISSUE THREAD

**Issue by anasouardini-old** [eclipse-ecal/fineftp-server#22]

**Comment by FlorianReimold** [comment]
Hi Anasouardini,

I am not really sure what this issue is about. FineFTP Server implements and FTP Server. If you need an FTP Client in your application I recommend libcurl for that. libcurl has been around for ages and is therefore widely used and very well tested.

For your next issue please take your time and create a proper issue. It is not fun to spend time helping you, if you don't spend time to properly explain what you need help with.
- Please use the headline to summarize your issue
- use the text-box to explain your issue with proper english sentences. Explain your goal and what your issue or question is. If you are having an issue, also explain how to got to that point.
