### ISSUE TITLE
Upload failure when file size is too big

### ISSUE THREAD

**Issue by fortunely** [eclipse-ecal/fineftp-server#31]
I upload a file(named "FASTSTARTKIT_TRK-MPC5604P_SDK.zip") with size 760 MB (797,657,236 byte) using Ftp Client FileZilla v3.59.0. In fact, it fails to transfer the file and error occurs, but the server responses with "226 Done"
Then I check the file uploaded on the server , and its size is only 314 MB (329,515,008 bytes) less than 760MB.

The following is FileZilla client log:
```text
Command:	CWD /
Response:	250 Working directory changed to /
Command:	TYPE I
Response:	200 Switching to binary mode
Command:	PASV
Response:	227 Entering passive mode (127,0,0,1,14,85)
Command:	STOR FASTSTARTKIT_TRK-MPC5604P_SDK.zip
Response:	150 Receiving file
Error:		Can't read “F:\Documents\FileZillaFTPRoot\linux\FASTSTARTKIT_TRK-MPC5604P_SDK.zip”。
Response:	226 Done
Error:		Transfer 329,515,008 bytes (use 4 seconds) , than fatal transfer error occurs.
```

**Comment by FlorianReimold** [comment]
Hi fortunely,

I have uploaded much bigger files (tested with many >4GiB files, as that is an important threshold), so I know that it works somehow. You copied the Log from FileZilla, right? I somehow recognize that format. FileZilla tells you it cannot read the file you are trying to upload. When FileZilla then closes the connection, the FTP Server assumes that the client has finished uploading and therefore responds `226 Done`. So the response is absolutely accurate here, but marks one of the great disadvantages of the FTP Protocol itself, as the server has no information whether the upload has been successful or if the connection terminated due to an error. This is only known by the client.
You can work around this general FTP disadvantage by uploading to a temporary name and then re-naming the file after a *successufull* transmission only. This technique will obviously only work if you have full control over what your client is doing, e.g. when using libcurl (so won't work with plain FileZilla). But if you handle it like that you can assume that all files with a "proper" file name are uploaded completely.

So can you please make sure that your FileZilla can actually read that file? Maybe try another one?

Regards
Florian

**Comment by fortunely** [comment]
Hi Florian,
Thanks for reply. The Log is from FileZilla, but I translate it to English.
You're right. I try another new file with bigger size, over 1GB, and I can upload it to fineftp-server(under Win10x64)  by FileZilla.

Then I want to check my primary file. So I try to extract that compressed file(.zip) using WinRAR, but it shows error message "Data check error(CRC check)". I think my file may have been broken.
