### ISSUE TITLE
426 Data transfer aborted: The provided file handle is invalid

### ISSUE THREAD

**Issue by yueyang212113** [eclipse-ecal/fineftp-server#72]
![image](https://github.com/user-attachments/assets/db47ea3c-4e24-47c5-a59a-d1d6aceb52d4)

windows 10
vs2022
amd64

**Comment by FlorianReimold** [comment]
fineftp-server only works in FTP Passive mode. There  are currently no plans to support the old-school active mode, as that mode is deprecated and leads to firewall issues. Microsoft unfortunately never updated ftp.exe to support FTP Passive mode.

Please use another FTP Client like curl, which is shipped with Windows since Windows 10. That will solve your issues.
